Repository Cwighty/nutrinova, pull requests merged in 2024-04, with the labels that each got.

#153 Fe edit patient
  NutrinovaData/obj/.EntityFrameworkCore.targets
  nutrinova-ui/src/app/(authorized)/patients/_components/PatientEditModal.tsx
  nutrinova-ui/src/app/(authorized)/patients/_components/PatientInfoForm.tsx
  nutrinova-ui/src/app/(authorized)/patients/_components/WarningModal.tsx
  nutrinova-ui/src/app/(authorized)/patients/page.tsx
  nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
  nutrinova-ui/src/app/(public)/addpatients/_components/PatientListItem.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#154 Simplify Meal Creation
  .devcontainer/.bashrc
  .devcontainer/Dockerfile
  nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
  nutrinova-api/NutrinovaApi/Controllers/MealController.cs
  nutrinova-api/NutrinovaData/Entities/FoodPlan.cs
  nutrinova-api/NutrinovaData/Extensions/FoodPlansExtension.cs
  nutrinova-api/NutrinovaData/Features/Meals/RecordMealRequest.cs
  nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFood.cs
  nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
  nutrinova-api/NutrinovaData/Rescaffold.sh
  nutrinova-api/NutrinovaData/ResponseModels/FoodResponse.cs
  nutrinova-api/NutrinovaData/ResponseModels/RecipeResponseModel.cs
  nutrinova-db/init-scripts/A_schema.sql
  nutrinova-ui/src/app/(authorized)/dashboard/_components/Cards/DailyCalories.tsx
  nutrinova-ui/src/app/(authorized)/food/_models/foodSearchResult.ts
  nutrinova-ui/src/app/(authorized)/food/foodHooks.ts
  nutrinova-ui/src/app/(authorized)/food/search/_components/SearchResultDataGrid.tsx
  nutrinova-ui/src/app/(authorized)/food/view/_components/MyFoodsSearchResultDataGrid.tsx
  nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/FilterMenu.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/MyFoodSearch.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/MyRecipeSearch.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/PreMealDetail.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/PrepMealCard.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/RecordMeal.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/RecordMealModal.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_components/SimpleAdd/SearchAll.tsx
  nutrinova-ui/src/app/(authorized)/meals/record/_models/preMealItem.ts
  nutrinova-ui/src/app/(authorized)/recipes/create/_models/recipe.ts
  nutrinova-ui/src/components/forms/SelectFoodDataGrid.tsx
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#155 Connect actual meals to meal card on dashboard
  nutrinova-ui/src/app/(authorized)/dashboard/_components/Cards/DailyCalories.tsx
  nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts
Labels: enhancement, Review effort [1-5]: 3
