Repository Cwighty/nutrinova, pull requests merged in 2024-03, with the labels that each got.

#143 Goal Detail Page
  nutrinova-ui/next.config.js
  nutrinova-ui/package-lock.json
  nutrinova-ui/package.json
  nutrinova-ui/src/app/(authorized)/dashboard/_components/Cards/DailyRecap/DailyRecapCard.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/DailyNutrientCarouselSelector.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/GoalsDetail.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientGoalChart/NutrientGoalChart.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientGoalChart/NutrientGoalRangeSummary.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientGoalChart/ProgressSummaryCard.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientGoalChart/TargetAmountChart.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientProgress.tsx
  nutrinova-ui/src/app/(authorized)/goals/_components/NutrientProgressProps.tsx
  nutrinova-ui/src/app/(authorized)/goals/goalHooks.ts
  nutrinova-ui/src/app/(authorized)/goals/page.tsx
  nutrinova-ui/src/components/PatientContextPageContainer.tsx
  nutrinova-ui/src/context/ThemeContext.tsx
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#145 Simply sign out when auth expires
  nutrinova-ui/src/components/providers/QueryClientNextProvider.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#146 Patient info page
  nutrinova-api/NutrinovaApi/Controllers/GoalController.cs
  nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
  nutrinova-api/NutrinovaData/Entities/Patient.cs
  nutrinova-api/NutrinovaData/Features/Patients/CreatePatientRequest.cs
  nutrinova-api/NutrinovaData/Features/Patients/PatientExtension.cs
  nutrinova-api/NutrinovaData/Features/Patients/PatientResponse.cs
  nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
  nutrinova-db/init-scripts/A_schema.sql
  nutrinova-ui/src/app/(authorized)/patients/_models/patient.ts
  nutrinova-ui/src/app/(authorized)/patients/page.tsx
  nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
  nutrinova-ui/src/app/(public)/addpatients/_components/PatientListItem.tsx
  nutrinova-ui/src/app/(public)/addpatients/page.tsx
  nutrinova-ui/src/app/(public)/welcome/page.tsx
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#148 Deleting patients
  nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/PatientControllerTests.cs
  nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
  nutrinova-db/init-scripts/A_schema.sql
  nutrinova-ui/src/app/(authorized)/patients/page.tsx
  nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#149 Recipe update tag
  nutrinova-api/NutrinovaApi/Controllers/RecipeController.cs
  nutrinova-ui/src/app/(authorized)/recipes/edit/_components/EditRecipeForm.tsx
  nutrinova-ui/src/app/(authorized)/recipes/view/_components/MyRecipesDetailCard.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#151 Number inputs
  nutrinova-ui/src/app/(authorized)/food/create/_components/CreateFoodForm.tsx
  nutrinova-ui/src/app/(authorized)/food/edit/_components/EditFoodForm.tsx
  nutrinova-ui/src/app/(authorized)/food/edit/_components/EditNutrientListItem.tsx
  nutrinova-ui/src/app/(authorized)/goals/CreateGoalModalContent.tsx
  nutrinova-ui/src/app/(authorized)/meals/edit/EditMealForm.tsx
  nutrinova-ui/src/app/(authorized)/meals/edit/EditMealModal.tsx
  nutrinova-ui/src/app/(authorized)/recipes/create/_components/ServingSizeUnitField.tsx
  nutrinova-ui/src/app/(authorized)/recipes/edit/_components/EditRecipeForm.tsx
  nutrinova-ui/src/components/forms/AmountInput.tsx
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#152 Edit patient back end
  nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/PatientControllerTests.cs
  nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
  nutrinova-api/NutrinovaData/Features/Patients/UpdatePatientRequest.cs
Labels: Review effort [1-5]: 4
